.class public Lcom/smilesword/myapplication/app/FakeSign;
.super Ljava/lang/Object;
.source "FakeSign.java"


# static fields
.field public static final s:Ljava/lang/String; = "MIIDlzCCAn+gAwIBAgIESkcaozANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJDQTETMBEGA1UE\nCBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEWMBQGA1UEChMNTmlhbnRpYywg\nSW5jLjEWMBQGA1UECxMNTmlhbnRpYywgSW5jLjEQMA4GA1UEAxMHVW5rbm93bjAeFw0xNjAzMTcy\nMDI4NDVaFw00MzA4MDMyMDI4NDVaMHwxCzAJBgNVBAYTAkNBMRMwEQYDVQQIEwpDYWxpZm9ybmlh\nMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRYwFAYDVQQKEw1OaWFudGljLCBJbmMuMRYwFAYDVQQL\nEw1OaWFudGljLCBJbmMuMRAwDgYDVQQDEwdVbmtub3duMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\nMIIBCgKCAQEAqoEoQvp2CXely+h2/gyOpN6soAGQpw20AajcxHzwQ7z0mXxAMWZ9fBQWjSj1w4iU\nafrRTmPkZgXW67+0tbGQXv/OskNFyaXDD1paavC3lNz1l2+fAVf3gMoGV2VWv3xBIRPg0e2/6SVQ\nECVdzQKKeOHH/DN8NhZF00Pxylt9RnupcE5DrNJjUaUOnSdk1fADSbSDhOaqlgE4zODOiVQfi3bi\nqN6Pq4ZEacf+GkgsYjcjGyDkcId0rcNlVv/J2jsHTGt5sbaRtthgW8s6tnN5vkypZxSjZCficJyq\nRjU0MUo36NeLZ7xc0eHURewpl+bjqxhB/hanIDcPR9hbD7FVcQIDAQABoyEwHzAdBgNVHQ4EFgQU\nY12xkIhowH9j3UPFm7Ej1zPfr8kwDQYJKoZIhvcNAQELBQADggEBAEXVFsjU7XanvTejzAF+ADq0\nZ0xViwEdxe0V5XUHX/mvLB0WI0lEs9ewlbi1wkXAbMBQbACTTjBfSTqkD4LhLVLw6mG/THIp6ozg\ncfunyHmSiPHLTZGxJy2L3YDTGj5CVs7uWNS1crXkSw1VTr0RhV8k7lDnPXEs0RS/FafyknyARaXG\nmJMlmjWmNgUGaqNEKcdT1vinRP1uWwVKT59ibmEGV8CloJR3R/OCyLjpEJzSsapyXyTVu1PBUFkz\nvWxKcG91EM1974leCn0FL7VPQFxKLiIeBlMU5NrhBFkUW5sRXNWjMLHFqMxJ53r9VVtAho5+RT8K\ndLQV1Va6S6oAH1U=\n"


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 13
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static getFakeSign()[B
    .locals 2

    .prologue
    .line 34
    const-string v0, "MIIDlzCCAn+gAwIBAgIESkcaozANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJDQTETMBEGA1UE\nCBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEWMBQGA1UEChMNTmlhbnRpYywg\nSW5jLjEWMBQGA1UECxMNTmlhbnRpYywgSW5jLjEQMA4GA1UEAxMHVW5rbm93bjAeFw0xNjAzMTcy\nMDI4NDVaFw00MzA4MDMyMDI4NDVaMHwxCzAJBgNVBAYTAkNBMRMwEQYDVQQIEwpDYWxpZm9ybmlh\nMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRYwFAYDVQQKEw1OaWFudGljLCBJbmMuMRYwFAYDVQQL\nEw1OaWFudGljLCBJbmMuMRAwDgYDVQQDEwdVbmtub3duMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\nMIIBCgKCAQEAqoEoQvp2CXely+h2/gyOpN6soAGQpw20AajcxHzwQ7z0mXxAMWZ9fBQWjSj1w4iU\nafrRTmPkZgXW67+0tbGQXv/OskNFyaXDD1paavC3lNz1l2+fAVf3gMoGV2VWv3xBIRPg0e2/6SVQ\nECVdzQKKeOHH/DN8NhZF00Pxylt9RnupcE5DrNJjUaUOnSdk1fADSbSDhOaqlgE4zODOiVQfi3bi\nqN6Pq4ZEacf+GkgsYjcjGyDkcId0rcNlVv/J2jsHTGt5sbaRtthgW8s6tnN5vkypZxSjZCficJyq\nRjU0MUo36NeLZ7xc0eHURewpl+bjqxhB/hanIDcPR9hbD7FVcQIDAQABoyEwHzAdBgNVHQ4EFgQU\nY12xkIhowH9j3UPFm7Ej1zPfr8kwDQYJKoZIhvcNAQELBQADggEBAEXVFsjU7XanvTejzAF+ADq0\nZ0xViwEdxe0V5XUHX/mvLB0WI0lEs9ewlbi1wkXAbMBQbACTTjBfSTqkD4LhLVLw6mG/THIp6ozg\ncfunyHmSiPHLTZGxJy2L3YDTGj5CVs7uWNS1crXkSw1VTr0RhV8k7lDnPXEs0RS/FafyknyARaXG\nmJMlmjWmNgUGaqNEKcdT1vinRP1uWwVKT59ibmEGV8CloJR3R/OCyLjpEJzSsapyXyTVu1PBUFkz\nvWxKcG91EM1974leCn0FL7VPQFxKLiIeBlMU5NrhBFkUW5sRXNWjMLHFqMxJ53r9VVtAho5+RT8K\ndLQV1Va6S6oAH1U=\n"

    const/4 v1, 0x0

    invoke-static {v0, v1}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v0

    return-object v0
.end method
